"""Headless e2e for saved properties: star on cards/table/map popup/drawer (mouse + keyboard), status + notes, Saved view
(status filter, sort, table, map, CSV export, copy folios), condo units, persistence across reload, JSON/CSV export + JSON import
(merge, and into a fresh browser). Screenshots -> shots/saved_*.png"""
import sys, time, csv, io, json
from playwright.sync_api import sync_playwright
URL = sys.argv[1] if len(sys.argv) > 1 else 'http://localhost:8080/'
SHOTS = '/workspace/parcel-finder/shots/'
errs = []
def ok(cond, msg):
    print(('PASS ' if cond else 'FAIL ') + msg)
    if not cond: errs.append('assert: ' + msg)
cnt = lambda pg: int(pg.inner_text('#sCount').replace(',', ''))
badge = lambda pg: int(pg.inner_text('#savedCount'))
def watch(pg, tag):
    pg.on('console', lambda m: m.type == 'error' and errs.append(f'{tag} console: ' + m.text))
    pg.on('pageerror', lambda e: errs.append(f'{tag} pageerror: ' + str(e)))
with sync_playwright() as pw:
    b = pw.chromium.launch()
    ctx = b.new_context(viewport={'width': 1360, 'height': 900}, accept_downloads=True)
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'], origin=URL.rstrip('/').rsplit('/', 1)[0] if URL.count('/') > 3 else URL)
    pg = ctx.new_page(); watch(pg, 'main')
    pg.goto(URL + '#ds=50&sort=ds_d'); pg.wait_for_selector('#results:not([hidden])', timeout=180000); pg.wait_for_timeout(1200)
    ok(badge(pg) == 0, 'starts with 0 saved')
    # card star by keyboard
    pg.focus('#cards .card:nth-of-type(1) .star'); pg.keyboard.press('Enter'); pg.wait_for_timeout(300)
    f1 = pg.get_attribute('#cards .card:nth-of-type(1)', 'data-folio')
    ok(pg.get_attribute('#cards .card:nth-of-type(1) .star', 'aria-pressed') == 'true' and badge(pg) == 1, f'keyboard Enter saves card 1 ({f1}); badge 1')
    ok(pg.evaluate("document.activeElement && document.activeElement.dataset.star") == f1, 'focus stays on the star after toggling')
    # card star by mouse, card itself opens with keyboard
    pg.click('#cards .card:nth-of-type(2) .star'); pg.wait_for_timeout(300)
    f2 = pg.get_attribute('#cards .card:nth-of-type(2)', 'data-folio'); ok(badge(pg) == 2 and not pg.query_selector('.drawer'), 'click star saves card 2 without opening the drawer')
    pg.click('#cards .card:nth-of-type(3) .star'); pg.wait_for_timeout(200); pg.click('#cards .card:nth-of-type(3) .star'); pg.wait_for_timeout(200)
    ok(badge(pg) == 2, 'second click unsaves (toggle)')
    # table row star
    pg.click('#vTable'); pg.wait_for_timeout(600)
    row = pg.query_selector_all('#tbody tr[data-id]')[3]; row.query_selector('.star').click(); pg.wait_for_timeout(300)
    ok(badge(pg) == 3 and not pg.query_selector('.drawer'), 'table row star saves without opening the drawer')
    pg.click('#vCards'); pg.wait_for_timeout(600)
    # drawer: status + note via keyboard-open card
    pg.focus('#cards .card:nth-of-type(1)'); pg.keyboard.press('Enter'); pg.wait_for_selector('.drawer #svStatusSel', timeout=60000)
    pg.select_option('#svStatusSel', 'Called'); pg.fill('#svNote', 'Left voicemail with owner 10/7; call back Friday'); pg.wait_for_timeout(900)
    ok('Saved in this browser' in pg.inner_text('#svNoteMsg'), 'note autosaves')
    pg.screenshot(path=SHOTS + 'saved_02_drawer.png')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(300)
    c1 = pg.inner_text('#cards .card:nth-of-type(1)')
    ok('Called' in c1 and 'Left voicemail' in c1, 'card shows status + note')
    # drawer save button on an unsaved property
    pg.click('#cards .card:nth-of-type(5)'); pg.wait_for_selector('.drawer .svsave', timeout=60000)
    pg.click('.drawer .svsave'); pg.wait_for_selector('.drawer #svStatusSel'); pg.select_option('#svStatusSel', 'Offer sent'); pg.wait_for_timeout(300)
    ok(badge(pg) == 4, 'drawer Save button saves (4)'); pg.keyboard.press('Escape')
    pg.evaluate("document.getElementById('results').scrollIntoView()"); time.sleep(0.3)
    pg.screenshot(path=SHOTS + 'saved_01_cards_stars.png')
    # condo unit (lazy pack)
    pg.goto(URL + '#type=condo&q=BRICKELL'); pg.wait_for_timeout(500); pg.reload(); pg.wait_for_selector('#results:not([hidden])', timeout=180000)
    pg.wait_for_function("document.querySelector('#cards .card')", timeout=180000); pg.wait_for_timeout(800)
    fc = pg.get_attribute('#cards .card:nth-of-type(1)', 'data-folio'); pg.click('#cards .card:nth-of-type(1) .star'); pg.wait_for_timeout(300)
    ok(badge(pg) == 5, f'condo unit saved ({fc}); 5 saved')
    # Saved view
    pg.goto(URL + '#ds=50&sort=ds_d'); pg.reload(); pg.wait_for_selector('#results:not([hidden])', timeout=180000); pg.wait_for_timeout(800)
    ok(badge(pg) == 5, 'persisted across reload: badge 5')
    pg.click('#savedBtn'); pg.wait_for_function("document.getElementById('sCount').textContent==='5'", timeout=120000)
    ok(cnt(pg) == 5 and 'saved=1' in pg.evaluate('location.hash'), 'Saved view shows all 5 (incl. condo); hash has saved=1')
    ok(pg.query_selector(f'#cards .card[data-folio="{fc}"]') is not None, 'condo unit appears in Saved view')
    pg.select_option('#sortSel', 'sv_d'); pg.wait_for_timeout(400)
    ok(pg.get_attribute('#cards .card:nth-of-type(1)', 'data-folio') == fc, 'sort Recently saved puts the condo first')
    pg.click('#svStatus .chip[data-st="Called"]'); pg.wait_for_timeout(400); ok(cnt(pg) == 1, 'status filter Called -> 1')
    pg.click('#svStatus .chip[data-st="Offer sent"]'); pg.wait_for_timeout(400); ok(cnt(pg) == 2, 'Called + Offer sent -> 2')
    pg.click('#svStatus .chip[data-st=""]'); pg.wait_for_timeout(400); ok(cnt(pg) == 5, 'All -> 5')
    pg.evaluate("window.scrollTo(0,document.getElementById('results').offsetTop-90)"); time.sleep(0.3)
    pg.screenshot(path=SHOTS + 'saved_03_saved_view.png')
    pg.click('#copyBtn'); pg.wait_for_timeout(300)
    try: clip = pg.evaluate('navigator.clipboard.readText()'); ok(len(clip.split()) == 5 and f1 in clip, 'Copy folios copies the 5 saved folios')
    except Exception as e: print('clipboard read unavailable:', e)
    pg.click('#vTable'); pg.wait_for_timeout(600)
    ok(len(pg.query_selector_all('#tbody tr[data-id]')) == 5 and len(pg.query_selector_all('#tbody tr .star.on')) == 5, 'table: 5 rows, all starred')
    pg.screenshot(path=SHOTS + 'saved_04_table.png')
    with pg.expect_download(timeout=180000) as dl: pg.click('#exportBtn')
    rows = list(csv.reader(io.StringIO(open(dl.value.path(), encoding='utf-8').read()))); hdr = rows[0]
    ok(len(rows) - 1 == 5 and 'Saved Status' in hdr and 'Saved Note' in hdr, f'Export CSV in Saved view: {len(rows)-1} rows with Saved columns')
    st = {dict(zip(hdr, r))['Folio']: dict(zip(hdr, r)) for r in rows[1:]}; ok(st.get(f1, {}).get('Saved Status') == 'Called', 'CSV status for card 1 = Called')
    # map: filter to one property, click it -> popup with star
    pg.click('#svStatus .chip[data-st="Called"]'); pg.click('#vMap'); pg.wait_for_function("document.getElementById('mapHint').textContent.includes('on the map')", timeout=180000); pg.wait_for_timeout(1500)
    box = pg.query_selector('#map').bounding_box(); pg.mouse.click(box['x'] + box['width'] / 2, box['y'] + box['height'] / 2); pg.wait_for_timeout(600)
    has_pop = pg.query_selector('.stackpop .star.on') is not None; ok(has_pop, 'map popup shows a filled star for the saved property')
    ok('Saved' in pg.inner_text('#mapLegend'), 'map legend lists Saved ring')
    pg.click('#svStatus .chip[data-st=""]'); pg.wait_for_timeout(1500)
    pg.evaluate("window.scrollTo(0,document.getElementById('results').offsetTop-90)"); time.sleep(0.6)
    pg.screenshot(path=SHOTS + 'saved_05_map.png')
    pg.click('#vCards'); pg.wait_for_timeout(500)
    # export JSON + CSV, unsave, import (merge)
    with pg.expect_download() as dl: pg.click('#svExportJson')
    data = json.load(open(dl.value.path())); ok(data.get('count') == 5 and any(x['note'].startswith('Left voicemail') for x in data['items']), 'Export JSON has 5 items with note')
    jpath = dl.value.path()
    with pg.expect_download() as dl: pg.click('#svExportCsv')
    srows = list(csv.reader(open(dl.value.path(), encoding='utf-8'))); ok(len(srows) - 1 == 5 and srows[0][4] == 'Status', 'Export saved CSV: 5 rows')
    pg.click(f'#cards .card[data-folio="{f2}"] .star'); pg.wait_for_timeout(600); ok(badge(pg) == 4 and cnt(pg) == 4, 'unsave in Saved view removes it (4)')
    pg.set_input_files('#svImport', jpath); pg.wait_for_timeout(1500); ok(badge(pg) == 5 and cnt(pg) == 5, 'Import JSON merges it back (5)')
    pg.reload(); pg.wait_for_selector('#results:not([hidden])', timeout=180000); pg.wait_for_function("document.getElementById('sCount').textContent==='5'", timeout=120000)
    ok(pg.get_attribute('#savedBtn', 'aria-pressed') == 'true', 'reload keeps Saved view on')
    pg.click(f'#cards .card[data-folio="{f1}"]'); pg.wait_for_selector('.drawer #svNote', timeout=60000)
    ok(pg.input_value('#svNote').startswith('Left voicemail') and pg.input_value('#svStatusSel') == 'Called', 'note + status persist across reload')
    pg.keyboard.press('Escape')
    # filter interaction leaves Saved view
    pg.click('#ideas .chip[data-i="1"]'); pg.wait_for_timeout(800); ok(pg.get_attribute('#savedBtn', 'aria-pressed') == 'false' and pg.query_selector('#savedBar').is_hidden(), 'picking an idea returns to search')
    # fresh browser: import the file
    ctx2 = b.new_context(viewport={'width': 1360, 'height': 900}); p2 = ctx2.new_page(); watch(p2, 'fresh')
    p2.goto(URL); p2.wait_for_selector('#results:not([hidden])', timeout=180000); ok(badge(p2) == 0, 'fresh browser has 0 saved')
    p2.click('#savedBtn'); p2.wait_for_timeout(500); p2.set_input_files('#svImport', jpath)
    p2.wait_for_function("document.getElementById('sCount').textContent==='5'", timeout=180000)
    ok(badge(p2) == 5 and p2.query_selector(f'#cards .card[data-folio="{fc}"]') is not None, 'fresh browser import: 5 saved incl. condo (condo pack lazy-loaded)')
    p2.evaluate("window.scrollTo(0,document.getElementById('results').offsetTop-90)"); time.sleep(0.3)
    p2.screenshot(path=SHOTS + 'saved_06_imported_fresh.png')
    # dark + mobile
    m = b.new_page(viewport={'width': 390, 'height': 844}, color_scheme='dark'); watch(m, 'mobile')
    m.goto(URL); m.evaluate(f"localStorage.setItem('mdpf.saved.v1', JSON.stringify(Object.fromEntries({json.dumps(data['items'])}.map(x=>[x.folio,x]))))")
    m.goto(URL + '#saved=1'); m.reload(); m.wait_for_selector('#results:not([hidden])', timeout=180000); m.wait_for_function("document.getElementById('sCount').textContent==='5'", timeout=180000)
    m.click(f'#cards .card[data-folio="{f1}"]'); m.wait_for_selector('.drawer #svNote', timeout=60000); m.wait_for_timeout(400)
    m.screenshot(path=SHOTS + 'saved_07_mobile_dark_drawer.png')
    print('ERRORS:', errs if errs else 'none')
    b.close(); sys.exit(1 if errs else 0)
